#! /bin/bash --

T="/$0" T="${T%/*}" T="${T#/}" T="${T:-.}" T="$( cd -- "$T" && pwd )" &&
source -- "$T/lib.sh" || exit

[[ -e "$T/m/etc/pacman.d/gnupg/gpg.conf" ]] \
    || $sudo cp -fru -t"$T/m/etc/pacman.d" /etc/pacman.d/gnupg

[[ -e "$T/m/var/lib/pacman/sync/core.db" ]] \
    || $sudo cp -fru -t"$T/m/var/lib/pacman" /var/lib/pacman/sync

$sudo rsync -lprDH --info=progress2 \
    /var/cache/pacman/pkg "$T/m/var/cache/pacman/"
