#! /bin/bash --

T="/$0" T="${T%/*}" T="${T#/}" T="${T:-.}" T="$( cd -- "$T" && pwd )" &&
source -- "$T/lib.sh" || exit

do_backup_remove_su "$T/m/etc/pacman.d/mirrorlist"
$sudo cp -fT --preserve=mode -- "$T/mirrorlist" "$T/m/etc/pacman.d/mirrorlist"
[[ -e "$T/m/root/${T##*/}" ]] || $sudo install -d -m755 "$T/m/root/${T##*/}"

find -H "$T" -mindepth 1 -maxdepth 1 \
    ! -name mirrorlist ! -name sha1sums.txt \
    ! -name '*-bootstrap-*' ! -name archlinux-bootstrap.tar.gz \
    ! -name m ! -name image.bin ! -name image.qcow2 \
    -exec $sudo cp -dfru -t"$T/m/root/${T##*/}" --preserve=mode -- '{}' +

U="$( do_chroot readlink -e -- "/root/${T##*/}" )"
user="${U#/home/}" user="${user%%/*}"
do_chroot chown -R -- "$user:$user" "$U"
