#! /bin/bash --

T="/$0" T="${T%/*}" T="${T#/}" T="${T:-.}" T="$( cd -- "$T" && pwd )" &&
source -- "$T/lib.sh" || exit

do_patch_su /etc/mkinitcpio.d/linux.preset "$T/i/patch/linux.preset"
$sudo rm -f /boot/initramfs-linux-fallback.img
$sudo mkinitcpio -plinux
