#! /bin/bash --

T="/$0" T="${T%/*}" T="${T#/}" T="${T:-.}" T="$( cd -- "$T" && pwd )" &&
source -- "$T/lib.sh" &&
source -- "$T/env.sh" || exit

do_restore_su /etc/mkinitcpio.d/linux.preset
$sudo mkinitcpio -plinux
