#! /bin/bash --

T="/$0" T="${T%/*}" T="${T#/}" T="${T:-.}" T="$( cd -- "$T" && pwd )" &&
source -- "$T/lib.sh" || exit

do_patch_su /etc/default/grub "$T/i/patch/grub-removable"
$sudo grub-install --target=x86_64-efi --recheck --removable \
    --efi-directory /esp
$sudo grub-mkconfig -o /boot/grub/grub.cfg
