colorscheme elflord
syntax enable
let g:is_bash=1

set spell
set spelllang=en,pl
set spellcapcheck=
set spellfile=~/.vim/spell/default.utf-8.add

set showmatch
set matchtime=2
set colorcolumn=81

if !filereadable(&spellfile) || getftime(&spellfile) > getftime(&spellfile . '.spl')
  exec 'silent mkspell! ' . fnameescape(&spellfile)

endif


function ISpace(n)
  set expandtab
  let &tabstop=a:n
  let &softtabstop=a:n
  let &shiftwidth=a:n

endfunction
command -nargs=1 ISpace call ISpace(<f-args>)
command -nargs=1 S ISpace <args>

function ITab(n)
  set noexpandtab
  let &tabstop=a:n
  let &softtabstop=a:n
  let &shiftwidth=a:n

endfunction
command -nargs=1 ITab call ITab(<f-args>)
command -nargs=1 T ITab <args>

function TWS()
  %s@\s\+$@@ge

endfunction
command TWS call TWS()

ISpace 2
set smartindent
set nowrap
set virtualedit=all
autocmd BufWrite * TWS


function CurRestore()
  if line("'\"") > 0 && line("'\"") <= line("$")
    exe "normal! g`\""
  endif

endfunction
command CurRestore call CurRestore()

set ignorecase
set smartcase
set hlsearch

set nowritebackup
set noswapfile
autocmd BufReadPost * CurRestore

set history=2000
set laststatus=2
set showcmd
set wildmenu
set display=truncate
set mouse=nvi
